user = input()
print('---------')
print('| {} {} {} |'.format(user[0], user[1], user[2]))
print('| {} {} {} |'.format(user[3], user[4], user[5]))
print('| {} {} {} |'.format(user[6], user[7], user[8]))
print('---------')